FROM python:3.13-alpine
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV ENV production

WORKDIR /supermarket-service

RUN apk add --no-cache patch && pip install --no-cache uv

COPY . .
RUN uv sync

WORKDIR /usr/local/lib/python3.13/site-packages
RUN patch -p1 < /supermarket-service/patches/strawberry-sqlalchemy.patch

WORKDIR /supermarket-service
EXPOSE 8000
CMD [ "uv", "run", "gunicorn", "src.main:app", "--bind", "0.0.0.0:8000", "-k", "uvicorn.workers.UvicornWorker" ]
