name: Build package & update submodule in control-room

on:
  push:
    branches:
      - main

jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    permissions:
#      contents: read
#      packages: write
#      attestations: write
#
#    steps:
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v3
#
#      - name: Setup Docker Buildx
#        uses: docker/setup-buildx-action@v3
#
#      - name: Login to GitHub Container Registry
#        uses: docker/login-action@v3
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Build and push
#        uses: docker/build-push-action@v5
#        with:
#          file: Dockerfile.prod
#          push: true
#          tags: ghcr.io/pi-findit/product-service:latest
#          platforms: "linux/amd64,linux/arm64"

  submodule:
#    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: PI-FindIt/control-room
          token: ${{ secrets.PRIVATE_TOKEN }}
          submodules: recursive

      - name: Setup GitHub Actions user
        uses: fregante/setup-git-user@v2

      - name: Update submodule
        run: git submodule update --recursive --remote

      - name: Commit & push changes
        run: |
          git commit -am "Update submodules" || echo "No changes to commit"
          git push